/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_witted_ptttalk_util_JitterBuffer */

#ifndef _Included_com_witted_ptttalk_util_JitterBuffer
#define _Included_com_witted_ptttalk_util_JitterBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    initJb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_initJb
  (JNIEnv *, jclass);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    openJb
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_openJb
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    closeJb
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_closeJb
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    addPackage
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_addPackage
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    getPackage
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_getPackage
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    getStatus
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_getStatus
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    getJbVer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_getJbVer
  (JNIEnv *, jclass);

/*
 * Class:     com_witted_ptttalk_util_JitterBuffer
 * Method:    deInitJb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptttalk_util_JitterBuffer_deInitJb
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
